### ISSUE TITLE
SmartyGUI ML-2.4 - Crash with BetterBlocks 3.7

### ISSUE THREAD

**Issue by accessdenied0** [ChessChicken-KZ/SmartyGUI#3]
There seem to be no issue, except if you look at an modified BetterBlock, like a Ladder or a Stone door.

It causes the game to crash with an IndexOutOfBoundsException:

`java.lang.ArrayIndexOutOfBoundsException: 4
	at BetterBlockLadder.getProperName(BetterBlockLadder.java:84)
	at BetterItemSubType.a(BetterItemSubType.java:23)
	at iz.l(SourceFile:226)
	at kz.chesschicken.smartygui.client.components.ModuleBlockRender.getSafeItemName(ModuleBlockRender.java:62)
	at kz.chesschicken.smartygui.client.components.ModuleBlockRender.updateBlock(ModuleBlockRender.java:77)
	at kz.chesschicken.smartygui.common.SmartyGUI.onTickGame(SmartyGUI.java:142)
	at kz.chesschicken.smartygui.commonloader.modloader.BaseModExtended.OnTickInGame(BaseModExtended.java:38)
	at ModLoader.OnTick(ModLoader.java:898)
	at EntityRendererProxy.b(EntityRendererProxy.java:16)
	at net.minecraft.client.Minecraft.run(SourceFile:781)
	at java.lang.Thread.run(Unknown Source)`

I provide an by the version of BetterBlocks I use:

[BetterBlocks 3.7 (Minecraft 1.7.3).zip](https://github.com/ChessChicken-KZ/SmartyGUI/files/9602651/BetterBlocks.3.7.Minecraft.1.7.3.zip)

I thank you alot for your efforts!

**Comment by ChessChicken-KZ** [comment]
Hello! Thanks for reporting this issue, I'll look at it as soon as possible.

Currently, I'm planning to refactor the mod a bit, so perhaps that part will be overridden.
